### ISSUE TITLE
Error while writing pointcloud2 msg to ply 

### ISSUE THREAD

**Issue by kartikpaigwar** [ANYbotics/point_cloud_io#13]
Failed to find match for field 'rgb'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.

**Comment by remod** [comment]
Does your pointcloud2 have these fields? I assume writing still succeeds, doesn't it?

**Comment by kartikpaigwar** [comment]
Yes, it still succeeds writing.

**Comment by remod** [comment]
Assuming that this problem has been due to the msg not containing these fields, closing the issue. Feel free to reopen if you suspect a problem in `point_cloud_io`.
