### ISSUE TITLE
Confirm behavior of Write node:  Doesn't apply transform for the pointcloud (from TF)

### ISSUE THREAD

**Issue by eric-schleicher** [ANYbotics/point_cloud_io#15]
Hi there...  In reviewing the code, it looks like the write node does a simple output of the PointCloud2 without the associated TF for the pointclouds reference frame?

Is that correct?

Do you have any tips on the best approach for adding this functionality?  

If i understand correctly, the caller would need to provide a reference frame from which to resolve the relative transform.

**Comment by remod** [comment]
Yes, it does not do any transformations. If you want to transform the point cloud before writing it into a file, you could add another simple node into your framework which does that for you and then sends the transformed point cloud to the writing node. You could use [this](https://answers.ros.org/question/262179/transform-pointcloud-with-tf2/) as a starting point.

**Comment by remod** [comment]
Assuming that the suggestion solves the question, I am closing the issue.
