### ISSUE TITLE
Problem Parsing header

### ISSUE THREAD

**Issue by boonflies** [ANYbotics/point_cloud_io#6]
I have problem trying to publish a .ply file generated with lsd_slam. I am able to open the .ply file with meshlab. But when I try to publish the .ply file, I get the following error,

[pcl::PLYReader] ~/catkin_ws/src/lsd-slam/src/lsd_slam/lsd_slam_viewer/pc.ply:1: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!

**Comment by pfankhauser** [comment]
This is typically a problem with the formatting of the .ply file. Can you check your .ply file in a text editor and compare it for example to [this example file](https://github.com/ethz-asl/ply_publisher/blob/feature/example/demo/cow.ply)?

**Comment by boonflies** [comment]
I opened the .ply file in meshlab, then exported it. On using the .ply file exported from meshlab, I was able to publish the pointcloud and visualize in RViz. 

The actual header of ply before opening in meshlab was,
ply
format binary_little_endian 1.0
element vertex 3044442
property float x
property float y
property float z
property float intensity
end header

and, after exporting from meshlab it became
ply
format binary_little_endien 1.0
comment VCGLIB generated
element vertex 814340
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 0
property list uchar int vertex_indices
end_header

The intensity has been removed. Is it possible to have ply published with intensity? Is it not essential to preserve intensity in pointcloud data? I am trying to use monocular camera with lsd_slam to create a map for path planning.

The entire pointcloud is completely visible in RED even from the start though the /point_cloud topic is being published for a time. I found a video where they port the pointcloud into RViz, which looks colorful, (https://www.youtube.com/watch?v=CUU3L6_wLXE). Is it because intensity data is removed out of pointcloud?

**Comment by pfankhauser** [comment]
Could you try to change the line 95 of `Read.cpp` to the format that you need?

    PointCloud<PointXYZRGBNormal> pointCloud;

**Comment by Gregoriomartjim** [comment]
Hello guys i am having the same problem , how did you fix it? i could not find your Read.cpp file anywhere 

Regards

**Comment by heimsi** [comment]
I had a similar issue, when opening a ply-file from a VO software I would get the following errors:
```[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:28: property 'float32 focal' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:29: property 'float32 scalex' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:30: property 'float32 scaley' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:31: property 'float32 centerx' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:32: property 'float32 centery' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:35: property 'float32 k1' of element 'camera' is not handled
[pcl::PLYReader] /home/ubuntu/mtdata/rtabOutput/rtabmapviz_exportcloud.ply:36: property 'float32 k2' of element 'camera' is not handled
```
Additionally, no cloud would be visible in Rviz even though `rostopic hz` showed that the pointcloud was published.

My issue was solved as indicated above by @boonflies  by importing the point cloud into Meshlab, and exporting it again to a .ply file. Using the newly exported file for the publisher, no unhandled properties would be shown, and the point cloud appear in Rviz.

**Comment by jovobe** [comment]
Hey guys,
I just saw this issue and want to add an idea, why this message is triggered by pcl: The .ply file which will be loaded may not contain a line feed at the end of the file. In my case the removal of that empty line fixed the problem.
Regards

**Comment by remod** [comment]
One issue can be that the file contains NaN or Inf values. Make sure you delete the corresponding points or replace these value before loading. https://github.com/PointCloudLibrary/pcl/issues/1433

**Comment by jveitchmichaelis** [comment]
This also doesn't work in CloudCompare unless you remove the camera calibration parameters. The NaNs are fine, they just get ignored.
